### ISSUE TITLE
Bright telescope picker

### ISSUE THREAD

**Issue by 0xricksanchez** [slugbyte/lackluster.nvim#15]
Hi,
firstly great theme! I just added this to [AstroNvim](https://github.com/AstroNvim/astrocommunity/commit/0d644e72c756de53eeaebd525ab5a629b0e184b4) for everybody to try!
I'm encountering a small problem regarding the telescope picker. It appears to be very bright with the wrong colors for me:

![image](https://github.com/slugbyte/lackluster.nvim/assets/17012133/eb2d0e04-5540-4fee-af54-fe61079f0e53)

**Comment by slugbyte** [comment]
Thanks for the bug report! 

Can you try running `hi clear` in your config before you set the colorscheme and see if that fixes it?

```lua
-- lua config would look like this
vim.cmd("hi clear")
vim.cmd.colorscheme("lackluster")
```

if that works I will try to make a patch soon :)

other than telescope does there seem to more issues?

**Comment by slugbyte** [comment]
Also wondering does your terminal support `true color`?  lackluster is a true color only color scheme... sorry I haven't put that in the readme yet. 

You many need to check that your `$TERM` env var is set to `screen-256color` or `xterm-256color`

in zsh/bash rc file it would look like `export TERM=screen-256color`

**Comment by 0xricksanchez** [comment]
For the sake of completeness. I'm using
- NVIM 0.10
- Kitty term 0.35.0
- Setting `export TERM=xterm-256color` has no effect in combination with Kitty

That said, I just noticed something. Opening the telescope picker for finding files/grepping stuff **does not** exhibit the above shown behavior! It's only when being in the color scheme selection picker of telescope... The preview works fine with other color schemes, e.g. `bamboo`:

![image](https://github.com/slugbyte/lackluster.nvim/assets/17012133/4df7652b-cc6e-4b7a-baed-d0eea5b10f41)


You can see that here, the bamboo theme preview matches what the theme is ultimately going to look like. This is the case for all the other themes I have available currently, except `lackluster` where this "Change color scheme"-telescope window turns white/black:

![image](https://github.com/slugbyte/lackluster.nvim/assets/17012133/953ebd08-11d7-4efa-95bb-af21d2f5a6e4)

Again, the theme correctly updates as shown in the NVIM window below the telescope picker. So it's a weird interaction between the theme and the telescope color scheme selection? Not sure what's going on currently

**Comment by slugbyte** [comment]
I just tried this, and cannot seem to reproduce your bug... hers a clip I recored of telescope

https://github.com/slugbyte/lackluster.nvim/assets/3581973/d0e1a906-3045-46a8-b959-c071a7bbdc13

I will look into it again tomorrow evening, hope to help you find a patch soon

I would also suggest running `:Lazy update lackluster.nvim` to double check your up to date, I made a few commits to main yesterday that where directly related to Telescope and I'm only sure that the current state of the `main` branch is working for me

**Comment by 0xricksanchez** [comment]
Interesting! Thanks for the update. I’ll look into this more tomorrow. Seems like it’s something on my end then actually… if it is I’m sorry in advance for the noise here 😬😬

**Comment by 0xricksanchez** [comment]
Ah I found my issue. It was actually a misconfiguration on my end. I had this snippet active in my config: https://github.com/AstroNvim/astrocommunity/blob/b2c7a4b43244316262872ea67ee82fead0f6f377/lua/astrocommunity/recipes/telescope-nvchad-theme/init.lua#L1

For some reason, it breaks the `lackluster` preview, but not others?

**Comment by slugbyte** [comment]
Nice find! Thanks for letting me know you found the source of the issue,  :)

**Comment by slugbyte** [comment]
marking this as sovled :)
