### ISSUE TITLE
add `extra/kitty`

### ISSUE THREAD

**Issue by slugbyte** [slugbyte/lackluster.nvim#23]
add support for [kitty](https://sw.kovidgoyal.net/kitty/) terminal (simular to extra/alacritty)

**Comment by slugbyte** [comment]
moving roadmap elsewhere

**Comment by jwarykowski** [comment]
@slugbyte is this still planned? Sorry, where did this move to?

**Comment by slugbyte** [comment]
this is still planned, It just moved to my personal todo list :)

**Comment by jwarykowski** [comment]
Hey @slugbyte, thanks for the quick response 🙇 No worries, sounds great, I can't promise I have the time to take a look but I'll see if I can squeeze in a quick look. Enjoy the break and the hour move! 🚚 🌴

**Comment by JuanBaut** [comment]
Hey, is help still wanted for the kitty theme? I can do it.

**Comment by slugbyte** [comment]
@JuanBaut that would be amazing! Because I don't use kitty :)

**Comment by slugbyte** [comment]
@JuanBaut With the allacritty theme I used orange instead of yellow when setting the terminal colors and I think it looks super nice, because lots of tools use yellow for printing warnings, and orange is the default warning color in lackluster :) 


I think orange should be the default for the base16 yellow and the yellow color should be a commented out opt in kinda thing

**Comment by JuanBaut** [comment]
hey there, excuse the delay. I just made the pull request

**Comment by slugbyte** [comment]
Awesome! Thanks so much @JuanBaut! I'll merge this evening, when I get home :)

**Comment by jwarykowski** [comment]
Hey @JuanBaut / @slugbyte, just spotted this come through on my lazy package updates... awesome work 🙌  Happy Friday! Thanks for adding this in and apologies for not getting around to this myself 😢🥳
