### ISSUE TITLE
opacity option support

### ISSUE THREAD

**Issue by ryoppippi** [slugbyte/lackluster.nvim#24]

**Comment by slugbyte** [comment]
I can look into it

**Comment by slugbyte** [comment]
I noticed in the [tokyonight.nvim configuration]https://github.com/folke/tokyonight.nvim?tab=readme-ov-file#%EF%B8%8F-configuration] they have a setting for `transparent` that does not set the background -> is this the feature your are requesting?

**Comment by ryoppippi** [comment]
Yes!!

**Comment by slugbyte** [comment]
A bit busy this week, but should have some time to make a feature to configure this as a default, It will take a medium size refactor of the colorscheme, but I was planning to do it anyway, in order to have some customization features like `transpaent` or `string_color` and quite a few more

for now if you want to do quick fix you can use thic code in config, 
```lua
        vim.cmd.colorscheme("lackluster-hack")
        vim.api.nvim_set_hl(0, 'normal', {
            fg = '#cccccc',
            bg = 'none'
        })
       -- this will not work if you switch colorschems but it will work if you are using lackluster as your default colorscheme :)
```

**Comment by slugbyte** [comment]
🎉 done :) 

I added docs in the main readme on how to setup transparency, or change menu,poup,telescope bg colors

You can also now tweek some of the syntax colors too, I found with different transparent backgrounds `comment` needed to be altered to be readable 

😆 from testing i now have a siik  dragon wallpaper

![Screenshot 2024-06-04 at 23 16 39](https://github.com/slugbyte/lackluster.nvim/assets/3581973/3c1f979f-6b76-4d50-9d41-ad6167e0745a)

**Comment by slugbyte** [comment]
lemme know if you have any trouble :)

**Comment by ryoppippi** [comment]
@slugbyte 
Thanks! that transparent mode is brilliant!!
I appreciate it!!!
❤️
