### ISSUE TITLE
Lualine active and inactive buffer have the same color

### ISSUE THREAD

**Issue by wkwhwh** [slugbyte/lackluster.nvim#25]
Really loving the theme. I tend to use buffers instead of tabs for my lualine tabline but I noticed that there is no contrast between active and inactive 

![CleanShot 2024-06-04 at 09 53 05@2x](https://github.com/slugbyte/lackluster.nvim/assets/7226788/73245ad7-6a23-4449-bc46-e861a28ccbc8)

- lackluster config

```
return {
  "slugbyte/lackluster.nvim",
  lazy = false,
  priority = 1000,
  init = function()
    -- vim.cmd.colorscheme("lackluster")
    vim.cmd.colorscheme("lackluster-hack") -- my favorite
    -- vim.cmd.colorscheme("lackluster-mint")
  end,
}
```

- lualine config

```
return {
	"nvim-lualine/lualine.nvim",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	config = function()
		local lualine = require("lualine")
		lualine.setup {
			tabline = {
				lualine_a = { 'buffers' },
				lualine_b = {},
				lualine_c = {},
				lualine_x = {},
				lualine_y = {},
				lualine_z = {}
			},
		}
	end
}

```

**Comment by slugbyte** [comment]
Thanks for the bug report! Glad to hear your enjoying the theme :)

I'll try and patch that later today!

**Comment by slugbyte** [comment]
hmmm, I have not been able to reproduce this issue, I just ran a test with 

```lua
require("lualine").setup({
  options = {
    theme = "lackluster",
  },
  tabline = {
    lualine_a = {"buffers"}
    -- i also separately tested lualine_b and lualine_c see screenshots below
  }
})
```

and got the following screenshots

## and then tabline with `lualine_a` looks like
![Screenshot 2024-06-04 at 19 23 30](https://github.com/slugbyte/lackluster.nvim/assets/3581973/f15a5650-8e43-4e54-ac07-9793edc48a18)

## and then tabline with `lualine_b` and `lualine_c` set to `"buffers"` booth look like
![Screenshot 2024-06-04 at 19 24 26](https://github.com/slugbyte/lackluster.nvim/assets/3581973/6621a138-eef8-41a8-9dc6-d83f5269fe0f)

can you give me an example of your lualine config?

**Comment by slugbyte** [comment]
let me know it that fixes your issue :)

**Comment by wkwhwh** [comment]
my bad, I completely forgot I needed to add the theme option. It works perfectly!

**Comment by slugbyte** [comment]
sweeet! glad that worked, happy hackin!
