### ISSUE TITLE
[Suggestion] Make Comments in lackluster-mint blend less with the background color

### ISSUE THREAD

**Issue by ybtre** [slugbyte/lackluster.nvim#32]
Loving the theme so far! My only issue is that the comments can blend and are hard to read because they are too close to the background color

![image](https://github.com/slugbyte/lackluster.nvim/assets/17096007/894d8c4d-a7cc-4655-bcdb-da2e2cf6ae39)

**Comment by ybtre** [comment]
maybe they can be close to the NOTE: color?

**Comment by slugbyte** [comment]
So glad you are enjoying the theme! Also thank you for the feed back! I totally get that comments are darker than what many people will probably prefer. I might give the comments a small lightness bump at some point, but I have been kind of enjoying how dark they are for now. 

I do have a solution for you though! A few days ago I added the ability to manually configure comment colors (and a few other things) for this very reason, I figure not everyone is going to have my same preferences. 

```lua
-- you need to call setup before you set colorscheme
lackluster.setup({
    -- You can overwrite the following syntax colors by setting them to one of...
    --   1) a hexcode like "#a1b2c3" for a custom color
    --   2) "default" or nil will just use whatever lackluster's default is.
    tweek_syntax = {
        comment = "#343434", -- this is the current value, you might want to try #444444
        -- there are more things you can update, check the (optinal) tweek colors and transparency section on the readme
    },
})

-- colorscheme must be set after after setup()!
vim.cmd.colorscheme("lackluster")
```

**Comment by slugbyte** [comment]
lemme know if this works for you :)

**Comment by ybtre** [comment]
Thank you! Both the slight lightening you did and the tweak you suggested work!
