### ISSUE TITLE
bug: error related to invalid key 'force' in nvim_set_hl function

### ISSUE THREAD

**Issue by Aliqyan-21** [slugbyte/lackluster.nvim#43]
### Did you check docs and existing issues?

- [X] I have read all the docs
- [X] I have searched the open and closed issues
- [X] I have added screenshots if relevant

### Whats your neovim version?

v0.9.1

### Operating System

linux

### Describe the bug

I set up the theme in my neovim colorscheme.lua and I got this error when I restarted neovim:
i was setting up a new theme in my neovim and I get this error:
Failed to run init for **lackluster.nvim**
...yanabid/.config/nvim/lua/aliqyan/plugins/colorscheme.lua:80: Vim:E5113: Error while calling lua chunk: .../share/n
vim/lazy/lackluster.nvim/lua/lackluster/init.lua:199: invalid key: force
stack traceback:
^I[C]: in function 'nvim_set_hl'
^I.../share/nvim/lazy/lackluster.nvim/lua/lackluster/init.lua:199: in function 'load'
^I...al/share/nvim/lazy/lackluster.nvim/colors/lackluster.lua:1: in main chunk
^I[C]: in function 'colorscheme'
^I...yanabid/.config/nvim/lua/aliqyan/plugins/colorscheme.lua:80: in function 'init'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:115: in function <...local/share/nvim/lazy/lazy.nvim/lu
a/lazy/core/loader.lua:114>
^I[C]: in function 'xpcall'
^I.../.local/share/nvim/lazy/lazy.nvim/lua/lazy/core/util.lua:131: in function 'try'
^I...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:114: in function 'startup'
^I...nabid/.local/share/nvim/lazy/lazy.nvim/lua/lazy/init.lua:112: in function 'setup'
^I/home/aliqyanabid/.config/nvim/lua/aliqyan/lazy.lua:14: in main chunk
^I[C]: in function 'require'
^I/home/aliqyanabid/.config/nvim/init.lua:2: in main chunk
# stacktrace:
  - colorscheme.lua:80 _in_ **init**
  - ~/.config/nvim/lua/aliqyan/lazy.lua:14
  - ~/.config/nvim/init.lua:2

### Expected Behavior

I expected the new theme to be applied.

### Additional context

I have fixed the bug and the theme is working fine now in my machine. I'll push the commit.

**Comment by slugbyte** [comment]
Hey @Aliqyan-21 Thanks so much for the bug report and the PR! Im sorry the colorscheme was giving you trouble!

I just looked over your PR and cannot seem to tell what you changed, I left a code review on the PR #44 to explain why I don't under stand what you changed, could you take a look at it and get back to me?

**Comment by Aliqyan-21** [comment]
Sir,
I have took a look, I think I pushed the wrong commit before but now I have
fixed it and committed on the branch the correct code, I have also provided
the link of the commit in comments of the pull request.

**Comment by slugbyte** [comment]
thanks for your help, your PR was merged, and then I figured out that the  issue was that `force` is only allowed in 0.10.0 and above, so I removed the only use of `force` in highlights

let me know if you still have any issues :)
