### ISSUE TITLE
suggestion: custom colors

### ISSUE THREAD

**Issue by JuanBaut** [slugbyte/lackluster.nvim#45]
### Did you read the docs?

- [X] I have read the docs.

### What would you like to change?

This is all personal opinion, I will list things in order of what I see as more important. I am also open to contribute and implement the things, although I am afraid I am a Lua beginner.

- Modifying the colors from lackluster.colors directly
- Making the end of file ~ character invisible.
- Changing the "Changed" highlight to lackluster.color.blue or something similar, in the same way "Removed" is orange, and "Added" is green.

### Why do you think this will improve lackluster?

I think those are changes that would allow lackluster to be more customizable and versatile, mostly because I think it is a great base grayscale color scheme to work on top of.

**Comment by slugbyte** [comment]
Thanks so much for the feedback! I'm glad you like the theme!

1. Color Tweaks (Approved)
I have been thinking about implementing your first suggestion for a while, and If you want to give it a shot I would be happy to let you create the implamentaion!

I would want the config to accept a `tweak_pallet` section that only allows people to change the colors in `lua/lackluster/color.lua` 

2. EndOfFile tweaks (Need To Test Some Ideas and Think About this)
I think this is a resonable change request, but I want to make some tests to see how I like it or if I think there should be some kind of toggle

for now if you want to manually set it
```lua
-- run this after you set your colorscheme
 vim.api.nvim_set_hl(0, 'EndOfBuffer', {fg = '#101010'}) 
```

4. Diff Tweaks (Approved)
I initially had the `theme.diff.change` color as blue, but I found that when I enabled things like git signs, It created a lot of more blue than I wanted, so I switched it to gray6. Its a personal preference thing that I want most of the visual indicators to be gray unless there is a specific error, or something to be warned about. 

im open to a `tweak_diff` config enhancement If you are entrested in implamenting that your self > I would look at the way tweaks

**Comment by slugbyte** [comment]
I decided just hide `EndOfBuffer` By default, I thinks it looks nice and I think it reduces unnecessary noise, which is an overall goal for the theme :)

**Comment by JuanBaut** [comment]
Hey. I just updated and that's already much better, thanks. About the rest:

1. ```tweak_palette```: I can try to implement it next week, and we can improve it from there.
2. ```EndOfBuffer```: We can work on a toggle later on, although I have to say this already looks much better.
3. ```tweak_diff```: Yes, I agree it's just personal preference, so I think it's totally fine to keep it as is. As you said, we would have to make tweak_diff options, although I'm not totally sure if it's worth it.

I will be working on tweak_palette on Monday 1st. I guess the rest will be on the queue and up to revision.

**Comment by slugbyte** [comment]
Thanks so much! Let me know if you have any questions :)

**Comment by slugbyte** [comment]
I added some Todo  Comments to help you figure out where to implement the tweak_pallet stuff. If you think they are wrong or incomplete just do what you thing works best, I just thought they might be helpful to get you started a little faster.

Just search for `JuanBaut` with telescope or grep to find them

![sc-2024-06-29-162249-todo-juan-baut](https://github.com/slugbyte/lackluster.nvim/assets/3581973/b36669f1-90a9-49d7-8ddf-5637b86c6013)

**Comment by slugbyte** [comment]
I had some free time this morning so I went ahead and added a `tweak_ui` section  to `setup()` that allows users to set `enable_end_of_buffer = true` and it will show the `~`s as gray4 again (PR #49)

but end_of_buffer will still be disabled by default

**Comment by JuanBaut** [comment]
Hey dude, I checked the todos, I didnt have much time today, but most likely tomorrow I will be on it. Thank you for the todos and the toggle.

**Comment by slugbyte** [comment]
Heck yee dude :) take ur time!

**Comment by JuanBaut** [comment]
hey dude, ive been a bit sick but today i am finally able to work on it. Im having issues setting up the plugin for development, i get this error.

<img width="1054" alt="Screenshot 2024-07-07 at 8 21 51 PM" src="https://github.com/slugbyte/lackluster.nvim/assets/90160941/d1b29a2c-a2b6-4a4e-9695-f27e2c2b847e">

this is my lazy setup of the plugin, it points to my fork
```lua
return {
	dir = "~/dev/neovim/lackluster.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
	},
	dev = true,
	lazy = false,
	priority = 1000,
	init = function()

		local lackluster = require("lackluster")
		lackluster.dev.create_usercmds() -- if I comment these lines it loads fine

		vim.cmd.colorscheme("lackluster")
	end,
}
```

**Comment by JuanBaut** [comment]
actually its mostly ok, the issue is within the create_usercmds() function, lackluster_reload() works fine, so I made myself a keymap to reload it and that works for now.

```lua
return {
	dir = "~/dev/neovim/lackluster.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
	},
	dev = true,
	lazy = false,
	priority = 1000,
	init = function()
		--local lackluster = require("lackluster")
		--lackluster.dev.create_usercmds()

		vim.keymap.set(
			"n",
			"<leader>0",
			"<cmd>lua require('lackluster').dev.lackluster_reload()<CR>",
			{ desc = "Reload lackluster" }
		)
		vim.cmd.colorscheme("lackluster")
	end,
}
```

**Comment by slugbyte** [comment]
Sorry you haven't been feeling well! 

Not sure what's wrong with the user commands, but they shouldn't be necessary for testing, the main thing I end up using is a keyboard shortcut that runs lackluster reload :) 

Hope you feel better soon, take it easy madude!

Good luck with everything :)

**Comment by slugbyte** [comment]
Your solution looks great, but I messed with your code a bit and realized that `theme.lua` needs to be completely refactored in order to support this feature... I have merged your branch into a tweak-color branch and am working on refactoring `theme.lua` now... Hopefully will be done with it this afternoon!

Sorry Its taken me a few weeks to get to this! Its been a hectic couple of weeks 😓

**Comment by slugbyte** [comment]
its been merged with main... the biggest change I had from your api was that I decided to rename `tweak_pallet` to `tweak_change`

@JuanBaut Let me know if you have any trouble getting it to work  :)
