### ISSUE TITLE
Undercurl

### ISSUE THREAD

**Issue by vadymbiliuk** [slugbyte/lackluster.nvim#48]
Hi. I'm enjoying your theme so much. But i didn't understand if there is possibility to turn on undercurl. Can you please support me with that?

**Comment by slugbyte** [comment]
Hey! So glad you are enjoying the theme! I'd be happy to help ya, but I need some more clarification :) 

Currently the theme only has undercurl enabled for spelling error related highlights, are those showing up for you?

I think some other themes turn on undercurl for diagnostics, is that what you are looking for? 

If so i would be happy to add support! 

If you are looking for undercurl support in a different way than spelling or diagnostics, please let me know :)

**Comment by slugbyte** [comment]
Also I am curious what terminal are you using, and if you using tmux?

**Comment by vadymbiliuk** [comment]
> I think some other themes turn on undercurl for diagnostics, is that what you are looking for?

I do look for diagnostics

> Also I am curious what terminal are you using, and if you using tmux?

Kitty, no tmux.
I have that for kitty.conf:
`enable_kitty_graphics yes`
And i had working curly underlines with github theme. Since i like this a lot i just need a few tweaks :)

> Currently the theme only has undercurl enabled for spelling error related highlights, are those showing up for you?

I don't have configuration for that type of stuff so i cannot tell unfortunatelly

**Comment by slugbyte** [comment]
I will try to add support for undercurl in diagnostics sometime tomorrow :) 

```
-- set this in your lua config to enable spell checking 
vim.opt.spell = true
```

**Comment by vadymbiliuk** [comment]
Thanks!

**Comment by slugbyte** [comment]
added undercurl support for diagnostics (PR #49)  

undercurl should be enabled by default if you upadate lackluste

(optional) I also decided that i prefer underline, so I added a `tweak_ui` section to the `setup()` config and you can set `disable_undercurl = true` to use underline instead of undercurl

Let me know if you still have any issues :)

**Comment by vadymbiliuk** [comment]
No issues, looks brilliant
