### ISSUE TITLE
suggestion: add .stylua.toml and end_of_buffer disabled change for transparent background

### ISSUE THREAD

**Issue by iton0** [slugbyte/lackluster.nvim#52]
### Did you read the docs?

- [X] I have read the docs.

### What would you like to change?

Firstly, thank you for the plugin; I have been really enjoying it. My first suggestion is to add a .stylua.toml to the repo and the second is to change the setting for end_of_buffer being disabled as 
```lua
-- Set the End-of-Buffer (EOB) character to an empty space for a cleaner appearance
vim.opt.fillchars:append({ eob = ' ' })
```

### Why do you think this will improve lackluster?

When the .stylua.toml file is included in the repository, it ensures that formatting is enforced according to its settings when users fork and make changes, overriding default formatting applied by plugins like conform.nvim.

The second suggestion ensures that when the end of the buffer is disabled, the end of the buffer character is a space, addressing the issue where users with a transparent background can still see the end of the buffer (screenshots in additional context).

### Additional context

Default configuration for end of buffer with transparent background:
![image](https://github.com/user-attachments/assets/7d54f60e-f717-4577-be0a-d64072109b90)

With changes suggested above:
![image](https://github.com/user-attachments/assets/013f5873-c945-42ea-b2ae-a1959b388054)

I have tried setting the fg for the EndOfBuffer highlight to none but results in EndOfBuffer character having a white fg

**Comment by slugbyte** [comment]
These are great suggestions! I think they should both be added to lackluster :) 

Currently I'm moving house, and it will take me anywhere from a few days to a week or so to get to this. Are you interested in contributing a PR? 

:) glad your enjoying lackluster!

**Comment by slugbyte** [comment]
Feel free to open a pr if that's something your interested in working on :)

**Comment by iton0** [comment]
I've opened PR #53 for adding the .stylua.toml and formatting Lua files. Should I create a separate PR for the transparent background refactor?

**Comment by slugbyte** [comment]
Finnally settled in at my new place and back on the computer :), I'm on working on getting  #50 fixed up and merged right now and will get to this next, should be this afternood or tomorrow morning :)

Sorry its taken me so long to get to this!
