### ISSUE TITLE
suggestion: Add ability to controll bold/italic font styles

### ISSUE THREAD

**Issue by vadymbiliuk** [slugbyte/lackluster.nvim#57]
### Did you read the docs?

- [X] I have read the docs.

### What would you like to change?

Add ability to controll bold/italic font styles.

### Why do you think this will improve lackluster?

Configuration will be more flexible and some people could miss this features

### Additional context

I tried to do it just for myself but for some reason it's not working for me.

I added something similar to what i saw in other libraries:
```
                spec.co('Bold', theme.none, theme.none, { bold = true }),
                spec.ln('markdownBold', 'Bold'),
                spec.ln('markdownBoldItalic', 'Bold'),
```

But this stuff is not working.
If this idea looks good for you and you can help me with understanding what exactly wrong overthere i could help with pr i think

**Comment by slugbyte** [comment]
Thanks for the suggestion! I will try to take a look at this sometime tomorrow and get back to you :) 

out of curiosity , are there many  more things other than `markdownBold` and `markdownBoldItalic` you are interested in modifying?

**Comment by vadymbiliuk** [comment]
I saw [this theme ](https://github.com/horanmustaplot/xcarbon.nvim) and i liked a lot how it looks with different font styles. Since i'm a noob in theming neovim i cannot say how many. Maybe you can use this stuff as reference but from what i saw there is italic for comments, functions etc

**Comment by slugbyte** [comment]
```lua


		local make_bold = function(name)
			local value = vim.api.nvim_get_hl(0, { name = name })
			value.bold = true
			vim.api.nvim_set_hl(0, name, value)
		end

		local make_italic = function(name)
			local value = vim.api.nvim_get_hl(0, { name = name })
			value.italic = true
			vim.api.nvim_set_hl(0, name, value)
		end

		vim.cmd.colorscheme("lackluster-hack")
                -- call make_bold and make_italic after setting the colorscheme
		make_bold("@keyword")
		make_italic("@keyword")
```

I haven't decided how I want to integrate bold/italic customiztion into the `setup()` func yet, but I made you some quick helper functions that you can do use to get some experimenting done :)

**Comment by vadymbiliuk** [comment]
Thanks!

**Comment by slugbyte** [comment]
@vadymbiliuk I just merge a solution supported by the `setup()` func  in PR #59 

heres some example code from the readme :)
 
```lua
local lackluster = require("lackluster")

-- !must called setup() before setting the colorscheme!
lackluster.setup({
    -- tweak_highlight allows you to update or overwrite the value passed into
    -- vim.api.nvim_set_hl which allows you to have complete control over modifying all
    -- highlights on a granular level.
    tweak_highlight = {
      -- modify @keyword's highlights to be bold and italic
      ["@keyword"] = {
        overwrite = false, -- overwrite falsey will extend/update lackluster's defaults (nil also does this)
        bold = true,
        italic = true,
        -- see `:help nvim_set_hl` for all possible keys
      },
      -- overwrite @function to link to @keyword
      ["@function"] = {
        overwrite = true, -- overwrite == true will force overwrite lackluster's default highlights
        link = "@keyword",
      },
    },
})

-- !must set colorscheme after calling setup()!
vim.cmd.colorscheme("lackluster")
```

Hope this is a better solution for you :) Thanks for the suggestion!
