### ISSUE TITLE
bug: WhiteSpace / NonText color not handeled

### ISSUE THREAD

**Issue by PsyNyde** [slugbyte/lackluster.nvim#69]
### Did you check docs and existing issues?

- [X] I have read all the docs
- [X] I have searched the open and closed issues
- [X] I have added screenshots if relevant

### Whats your neovim version?

v0.9.5

### Operating System

nixos btw :p

### Describe the bug

![2024-09-09-07-47-58](https://github.com/user-attachments/assets/6b26070e-8c63-48f1-9635-3ba78a176ba3)

### Expected Behavior

as the title suggests, whitespace character isn't handled. So it kinda looks out of place as shown in the 1st window and the 2nd one is somewhat expected.

**Comment by PsyNyde** [comment]
while we're at it i think `FloatBorder` highlight also could be something better.
This is with default pallet:

![img](https://cdn.discordapp.com/attachments/976958356872908800/1282658413129764875/image.png?ex=66e0283c&is=66ded6bc&hm=f420e81124ff0341c1390cf74238e3c14b7a28deb9dfa72770a5fc839526fd2e&)

This is with `Floatborder` `guibg=#101010`:

![img](https://cdn.discordapp.com/attachments/976958356872908800/1282659759547351142/image.png?ex=66e0297d&is=66ded7fd&hm=bc627e47aadbcc20ecd30aafbe848a0698b151dd5c2d1fab7201a5d261b6f242&)

**Comment by slugbyte** [comment]
@PsyNyde thanks for the bug report!

For the whitespace bug, Did you find a specific highlight that fixed your whitespace issue, I'm not able to reproduce on my setup.

For the border feature suggestion: I'm a fan of borderless popups, but I'm willing to add an `setup()` toggle to add visible borders for popups :) 

I'm afk for the next two days, but can probably get to this Wednesday evening :)

**Comment by PsyNyde** [comment]
> For the whitespace bug, Did you find a specific highlight that fixed your whitespace issue, I'm not able to reproduce on my setup.

to reproduce the issue you'll need
```lua
vim.opt.list = true
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
```
these options to be set. for list the highlight group is literally called `WhiteSpace` which is by default links to `NonText` highlight group. So defining `NonText` should suffice the issue. You can search them using `:Telescope highlights` if necessary.
> For the border feature suggestion: I'm a fan of borderless popups, but I'm willing to add an `setup()` toggle to add visible borders for popups :)

Changing the highlight shouldn't enable border for non border users. border visibility is managed through plugin specific settings for example
```lua
window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
},
```
in cmp-nvim this enables border regardless of any highlight. I was just making sure if `FloatBorder` is used elsewhere where changing this could negatively effect its visually.
> I'm afk for the next two days, but can probably get to this Wednesday evening :)

i'd have send a pr but unfortunate i got exams next month :( although i fixed mine through vim cmd (as seen in the code in border issue screenshot) for now so no rush from my part

**Comment by slugbyte** [comment]
Thanks for the thorough response, that's exactly the information I needed! I should be able to patch all this tomorrow :) 

Good luck with exams!

**Comment by slugbyte** [comment]
I closed the issuer because I just merged a PR that patches this bug, now NonText is Gray5 and Whitespace is Gray4

I also created a new suggestion issue to track the float boarder proposal :)
