### ISSUE TITLE
bug: `Folded` & `FoldColumn` no handled.

### ISSUE THREAD

**Issue by PsyNyde** [slugbyte/lackluster.nvim#74]
### Did you check docs and existing issues?

- [X] I have read all the docs
- [X] I have searched the open and closed issues
- [X] I have added screenshots if relevant

### Whats your neovim version?

v0.9.5

### Operating System

nixos

### Describe the bug

![image](https://github.com/user-attachments/assets/e3b93e9c-c3fe-45df-8e3c-68610c02c3fe)
As seen in the screenshot fold highlights aren't handled. Addressing `Folded` & `FoldedColumn` should be sufficient for the issue.

### Expected Behavior

Maybe the bg same as editor bg but fg something a bit more noticeable color. I'd love to see others opinion in this.

### Additional context

On a separate note do you have any plan for lackluster support outside of neovim? I've created lackluster theme for `steam` and `bat` (and `gtk` technically) for my machine and I'd be happy to share them if anyone is interested.

**Comment by slugbyte** [comment]
Yo thanks @PsyNyde for another bug report, super helpful!!! :) 

I will try and add Fold related highlights on Monday. :) 

As for the non neovim related colorschemes, some others and I have added a few in the /extra dir! I would be happy to include yours too! Just submit a submit a PR :) 

As I side project for fun (which I haven't gotten to work on for a bit) I have started making a little zig program to generate the extra colorscheme files, so that eventually I could have a cli that peeps could run to generate themes with color variations :)

**Comment by PsyNyde** [comment]
> As I side project for fun (which I haven't gotten to work on for a bit) I have started making a little zig program to generate the extra colorscheme files, so that eventually I could have a cli that peeps could run to generate themes with color variations :) in /util

I generated my eza colorscheme using your zig tool, it's great. Instead of hardcoding them generating them is a better approach for future changes and variations imo.

You can have a look at [stylix](https://github.com/danth/stylix/tree/master/modules) for inspirations for generating configs. i used stylix in on my machine to generate most of the custom theme like gtk, firefox etc.

It uses [base16 specs](https://github.com/tinted-theming/home/blob/main/styling.md) to generate themes. for example i used <details align="center"><summary><samp>these to generate</samp></summary>

![image](https://github.com/user-attachments/assets/e46bcbd2-e156-474a-8d9b-4d2e3a2c496a)
</details>

And you don't need to take this as your highest priority 😄. I've seen people burn out from these type of stuff, keep it as a side project as it's now :3

**Comment by slugbyte** [comment]
dang, thats a siik project! :)

I just merged some highlights for folded and foldcolumn, I decited to go with a very simple fg only gray4, it kinda looks like a comment, but because of the fold `.....................` its still visualy identifyable as a fold :)
