### ISSUE TITLE
proposal: support indentmini.nvim

### ISSUE THREAD

**Issue by mosaab2020** [slugbyte/lackluster.nvim#75]
### Did you read the Contributing Guide?

- [X] I have read the Contributing Guide

### Description

i started using [indentmini.nvim](https://github.com/nvimdev/indentmini.nvim)

i would add highlights for indentmini.nvim

how it look out of the box:
![Screenshot_indentmini](https://github.com/user-attachments/assets/b0ae7ab2-2844-45f7-a06a-85a85a541a91)

there should be a highlight for the the scope the cursor in, and a highlight for the scope the cursor in not in.

**Comment by mosaab2020** [comment]
There are two highlights:

IndentLine
IndentLineCurrent

i will make a pull request as soon as possible!

**Comment by mosaab2020** [comment]
i set IndentLineCurrent to lack, and IndentLine to gray4
![Screenshot_indentmini_fix](https://github.com/user-attachments/assets/00a462e0-64fc-4bd8-9803-fc172829f160)

**Comment by mosaab2020** [comment]
so what do you think?

**Comment by slugbyte** [comment]
I just played with your pr and made a variation thats dimmer grays #77 

I've been trying to keep non code highlights darker grays, and less colorful more and more the longer I've worked on lackluster, I think it helps create a visual separation from code and UI, while allowing the code to be in focus and the UI to be visible enough to be useful if you need to pay attention to it :) Not sure if that makes sence, my goal is for code to stand out and UI to sort of fade into the background, but still be usefull :)

Thanks for the PR!

**Comment by mosaab2020** [comment]
> I've been trying to keep the non-code highlights (UI) darker gray and less colorful more and more as i continue working on lackluster. I think it helps create a visual separation between code and UI, allowing the code to be in focus by being brighter and the UI to be darker but visible enough to be useful if you need to pay attention to it :) Not sure if that makes sense, my goal is for code to stand out and UI to sort of fade into the background, but still be usefull :)

i like it! but many be you could add 

> keep the non-code highlights (UI) darker gray and less colorful

to the CONTRIBUTING guide in the lackluster goals section. no pressure :)

**Comment by mosaab2020** [comment]
closing this issue
