### ISSUE TITLE
bug: `invalid key: overwrite` error

### ISSUE THREAD

**Issue by k14lb3** [slugbyte/lackluster.nvim#80]
### Did you check docs and existing issues?

- [X] I have read all the docs
- [X] I have searched the open and closed issues
- [X] I have added screenshots if relevant

### Whats your neovim version?

NVIM v0.10.2

### Operating System

Arch Linux x86_64

### Describe the bug

Error is thrown when tweaking a highlight group and adding `overwrite = false`.

![image](https://github.com/user-attachments/assets/eb96e5ef-16bc-4699-99fc-bbdb43b4564f)

![image](https://github.com/user-attachments/assets/5a7dd54c-b04d-4703-842a-70e2229ca03e)

### Expected Behavior

Should not throw an error.

**Comment by slugbyte** [comment]
🎉 thanks so much!
