### ISSUE TITLE
proposal: Light variant using vim.o.background

### ISSUE THREAD

**Issue by hocman2** [slugbyte/lackluster.nvim#83]
### Did you read the Contributing Guide?

- [X] I have read the Contributing Guide

### Description

Hey,

I've already worked on this on my fork.
The idea is to automatically switch the color palette based on the vim.o.background value, not to have a different theme specifically for light mode.

This required numerous changes in the _lackluster/init.lua_ and _lackluster/tweak.lua_ files as well as the addition of _lackluster/*-light.lua_ files for color palettes

1. The color palette is refetched dynamically between the _x.lua_ and _x-light.lua_ files, this avoids having both color palettes in memory at all time
2. If the variant changes, the theme is recreated in the load function, all color tweaks are reapplied after the color has been updated. This is necessary because colors may be different.
3. When creating tweaks, it's now possible to use the key of a color as a string to adjust it automatically between it's light/dark variant

### Link

https://github.com/hocman2/lackluster.nvim/tree/light-variant

### Additional context

<img width="554" alt="Capture d’écran 2024-11-21 à 10 53 14" src="https://github.com/user-attachments/assets/ac8251b0-608e-4334-ab22-b04be4d5f79b">

**Comment by slugbyte** [comment]
Hey @hocman2! Thanks for the proposal! I did have plans for creating a light variant I the future, and have also played around with getting one working. However recently I had my first kid and am taking a break from work and projects like this for a few months to settle in to family life :) 

It Looks like you have done some awesome work in your fork! But for now I'm going to have to say sorry and pass on accepting the proposal. 

In a few months I might reconsider if I find the time and I’ll let you know here :) 

Sorry about that!

**Comment by hocman2** [comment]
no worries, take care of your family first ! I can still work in light mode on my end so it's all good

**Comment by mikker** [comment]
Using your branch @hocman2. Congrats on the kid @slugbyte! I hope this gets upstreamed some day 😊
