### ISSUE TITLE
proposal: add ghostty configuration file

### ISSUE THREAD

**Issue by lanjoni** [slugbyte/lackluster.nvim#84]
### Did you read the Contributing Guide?

- [X] I have read the Contributing Guide

### Description

Add a simple [ghostty](https://ghostty.org) configuration file.

**Comment by slugbyte** [comment]
Sorry for delay I'm on paternity leave and not really keeping up with GitHub rn :) 

Thanks for the pr!!

**Comment by lanjoni** [comment]
Don't worry! Congratulations! 🎉
